spring:
  database:
    driver-class-name: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://localhost:3306/oshop"
    username: "root"
    password: '{cipher}944d8d40f1cc9a4dbe7bba6f5c26272be172a353091e385835d81bf2e071634f'
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rupeshsmorajkar/myshop
          username: rupeshsmorajkar@gmail.com
          password: '{cipher}292af5b19a04c7b6409e131ed3847389971acbae1bf6db9cd5923afa3d7622c2'
          search-paths: products, myshop
        encrypt:
          enabled: false

security:
  basic:
    enabled: false

server:
  port: 8081

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG
   
configuration:
  logging:
    application:
      name: MyCompany
      directory: c:/myapp/resources
     

