server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5
    
spring:
  devtools:
    livereload:
      enabled: false

   
 